<?php
/**
 * Canalweb_Actus extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Canalweb
 * @package        Canalweb_Actus
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Actu link widget template
 *
 * @category    Canalweb
 * @package     Canalweb_Actus
 * @author      Ultimate Module Creator
 */
?>
<?php $_actu = $this->getCurrentActu();?>
<?php if ($_actu) :?>
    <div class="actu-widget-link">
        <a href="<?php echo $_actu->getActuUrl()?>"><?php echo $_actu->getTitle()?></a>
    </div>
<?php endif;?>
